### PR TITLE
Add support for network packets / udhcp + doc update

### PR DESCRIPTION
**Pull request by zguig52**
With this additional parameters, it is now possible to add auto DHCP address on boot (with System configuration / Network interface to configure through DHCP ). With it, others packages like dropbear are autostarted:
Before:
Starting network: udhcpc: started, v1.33.0
udhcpc: socket: Address family not supported by protocol
FAIL

After:
Saving random seed: [   17.393576] random: dd: uninitialized urandom read (512 bytes read)
OK
Starting network: udhcpc: started, v1.33.0
udhcpc: sending discover
udhcpc: sending discover
udhcpc: sending select for X.X.X.X
udhcpc: lease of X.X.X.X obtained, lease time 43200
deleting routers
adding dns X.X.X.X
OK
Starting dropbear sshd: OK

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @zguig52, looks good. I'm just not sure to understand why the `sys_clk_freq` is lowered to 50MHz, is there a reason?

**Comment by zguig52** [comment]
Hi @enjoy-digital, I had to change the master clock to pass placement/routing without any warning on the final timing analysis, being single or multicore configuration with all peripherals (ethernet, sdcard, ...). As you advised me on the IRC channel, when I remove ethernet and sdcard, I can go to 75MHz.
On a 1 CPU conf, I never managed to get more than 70MHz (often it gets to 68MHz) with all peripherals.
On a 4 CPU conf, just did a synthesis now, I get 51.55 MHz

BTW, I have some questions about multicores booting, but we might discuss this in another topic.

**Comment by enjoy-digital** [comment]
@zguig52: Thanks, this makes senses. This also explain why the boot was slower on your configuration. Could you just fix the merge confict (related to https://github.com/litex-hub/linux-on-litex-vexriscv/commit/5c9054b7d9dea3b875332aeebded15fc3a9c8fea I think) and I could merge. We could always use the 50MHz clock for now and eventually increase it later if improvements are made of use different frequencies depending the configuration.

**Comment by enjoy-digital** [comment]
Thanks, merged.

**Pull request merged**
