### PR TITLE
Switch to VexRiscv SMP + Linux 5.10 + OpenSBI 0.8

### PR DESCRIPTION
**Pull request by enjoy-digital**
This PR switches the CPU to VexRiscv-SMP (CPU count can be selected: 1, 2, 4 or even more) and to upstream Linux (5.10) and OpenSBI (0.8). To simplify the project and maintenance, the VexRiscv-Linux variant will no longer be supported (The resource usage of VexRiscv-SMP with CPU count set to 1 is equivalent to the VexRiscv-Linux variant).

### CODE REVIEW

**Comment by mateusz-holenko** [comment]
`json2dts.py` is now a part of the litex repo (https://github.com/enjoy-digital/litex/blob/f777cddefe83581321ba387a4e1e977d6ebf7d2e/litex/tools/litex_json2dts.py), so I guess that the changes should be PRed there first, right?

**Comment by enjoy-digital** [comment]
Thanks @mateusz-holenko, indeed. I'm thinking doing the opposite: merge this PR (with local json2dts.py) and then integrate the json2dts changes in LiteX (as we did in fact with the non-SMP version).

**Comment by mateusz-holenko** [comment]
> Thanks @mateusz-holenko, indeed. I'm thinking doing the opposite: merge this PR (with local json2dts.py) and then integrate the json2dts changes in LiteX (as we did in fact with the non-SMP version).

Sure, that sounds good too!

BTW, we have an additional fix for the script that changes generation of SDCard CSR registers: https://github.com/antmicro/linux-on-litex-vexriscv/commit/fd0cc0ddfe022d53c38725ab86460e21d541c0f0. Do you think it could be included in this PR, @enjoy-digital?

**Comment by mateusz-holenko** [comment]
On the other hand I see that the `litex_mmc.c` driver evolved in https://github.com/litex-hub/linux/commit/49ce8134c4e23d36e5d42a55402069a0948cfce5, so maybe our proposed changes to `json2dts.py` are not necessary anymore - @gsomlo, @enjoy-digital?

**Comment by enjoy-digital** [comment]
@mateusz-holenko: Thanks I'll have a look at your changes. I'm currently doing tests but on the various boards and fixing other aspects (related to SMP). Once done, I'll do more test with the SDCard driver and integrate the changes if required.

**Comment by gsomlo** [comment]
> On the other hand I see that the `litex_mmc.c` driver evolved in [litex-hub/linux@49ce813](https://github.com/litex-hub/linux/commit/49ce8134c4e23d36e5d42a55402069a0948cfce5), so maybe our proposed changes to `json2dts.py` are not necessary anymore - @gsomlo, @enjoy-digital?

@mateusz-holenko For my part, I'm not sure what relationship commit `49ce8134c4e23d36e5d42a55402069a0948cfce5` has to the `litex_mmc` driver. Either way, any changes I made in the [litex-rocket-rebase](https://github.com/litex-hub/linux/tree/litex-rocket-rebase) branch preserve the expected DTS format used by Antmicro's (dma-enabled) version.

**Comment by mateusz-holenko** [comment]
@gsomlo you are right - I was not precise enough ;) 
There are no litesdcard-related changes directly in `49ce8134c4e23d36e5d42a55402069a0948cfce5 `, but this commit is selected as `HEAD` for linux in the `vexriscv-smp` branch (and this tree includes a lot of your commits to `litex_mmc.c`).
If there were no changes to the DTS format we proposed, than probably fixes to `json2dts.py` are required, but this is to be verified by @enjoy-digital.

**Comment by enjoy-digital** [comment]
@mateusz-holenko, @gsomlo: The fix is here to reduce the kernel Image size that largely increase without (17MiB instead of 6MiB).

**Comment by gsomlo** [comment]
Oh, I don't seem to have access to the vexriscv-smp branch
(via https://github.com/litex-hub/linux), which is why I
couldn't figure out where that commit came from...

**Comment by mateusz-holenko** [comment]
It's not my day :( I meant this branch (i.e., https://github.com/litex-hub/linux-on-litex-vexriscv/tree/vexriscv-smp) and referred to this particular change: https://github.com/litex-hub/linux-on-litex-vexriscv/pull/165/files#diff-5f53383bed071cb5928ececad307d6db094231f840e1ca0e8a94557781a23aa3L32-R31

**Pull request merged**
