### PR TITLE
Add support for LiteX PWM

### PR DESCRIPTION
**Pull request by mateusz-holenko**
This adds Linux driver for LiteX PWM, enables it on `soc_linux` platform and adds "pwm" capability for Arty board.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks, that's merged. I just adapted the code a little bit to control a rgb_led with pwm instead of using one of the user led: https://github.com/litex-hub/linux-on-litex-vexriscv/commit/4ec1ec2fc53be052c89698ac78b1a7fe1af31e54, this now creates 3 pwms: 1 for each color.

**Comment by enjoy-digital** [comment]
Can you describe how to use the PWM module from Linux? (I'm trying to sum up things here: https://github.com/litex-hub/linux-on-litex-vexriscv/issues/44)

**Comment by mateusz-holenko** [comment]
@enjoy-digital This is how to test PWM on Linux:

<pre>
cd /sys/class/pwm/pwmchip0
echo 0 > export
cd pwm0
echo 100 > period
echo 50 > duty_cycle
echo 1 > enable
</pre>

This should turn the LED on at 50% of brightness - you can control it by changing `duty_cycle` value from 0 to `period`.

**Comment by enjoy-digital** [comment]
Thanks!

**Pull request merged**
