### PR TITLE
Add mmc/sd

### PR DESCRIPTION
**Pull request by mateusz-holenko**
This adds support for SD Card:

* provides the Linux driver,
* extends Arty target.

Tested using Pmod MicroSD: https://store.digilentinc.com/pmod-microsd-microsd-card-slot/

### CODE REVIEW

**Comment by mateusz-holenko** [comment]
Testing instructions:

1. During boot you should see the following lines in the log:
```
[    3.907468] litex-mmc f000a800.mmc: Setting clk freq to: 0
[    3.926727] litex-mmc f000a800.mmc: Setting clk freq to: 10000000
[    3.968631] litex-mmc f000a800.mmc: Setting clk freq to: 25000000
[    3.982844] mmc0: new SDHC card at address 1234
[    4.003202] blk_queue_max_hw_sectors: set to minimum 8
[    4.003936] blk_queue_max_segment_size: set to minimum 4096
[    4.004877] mmcblk0: mmc0:1234 SA16G 14.4 GiB 
[    4.216082]  mmcblk0: p1
```

2. Simple read test:
```
root@buildroot:~# hdparm -tT /dev/mmcblk0
/dev/mmcblk0:
Timing buffer-cache reads:    14 MB in 0.53 seconds = 26762 kB/s
Timing buffered disk reads:    2 MB in 4.31 seconds = 474 kB/s
```

3. Mounting the SD card in the filesystem:
```
root@buildroot:~# mkdir sdcard
root@buildroot:~# mount /dev/mmcblk0p1 sdcard
[  163.419996] EXT4-fs (mmcblk0p1): recovery complete
[  163.451384] EXT4-fs (mmcblk0p1): mounted filesystem with ordered data mode. Opts: (null)
```

4. Write test:
```
root@buildroot:~# yes "Testing sdcard write speed" | dd of=inputtestfile.txt bs=
512 count=1000; sync
1000+0 records in
1000+0 records out
root@buildroot:~# time dd if=inputtestfile.txt of=sdcard/outputtestfile.txt bs=5
12 count=1000; sync
1000+0 records in
1000+0 records out
real	0m 1.19s
user	0m 0.07s
sys	0m 1.10s
root@buildroot:~# ls -la sdcard/outputtestfile.txt 
-rw-r--r--    1 root     root        512000 Jan  1 00:09 sdcard/outputtestfile.txt
root@buildroot:~# head sdcard/outputtestfile.txt
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
root@buildroot:~# tail sdcard/outputtestfile.txt
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
Testing sdcard write speed
```

5. Unmounting / mounting again and listing the content of the card:
```
root@buildroot:~# umount sdcard
root@buildroot:~# mount /dev/mmcblk0p1 sdcard
[  667.107812] EXT4-fs (mmcblk0p1): mounted filesystem with ordered data mode. Opts: (null)
root@buildroot:~# ls -la sdcard/outputtestfile.txt
-rw-r--r--    1 root     root        512000 Jan  1 00:09 sdcard/outputtestfile.txt
```

**Comment by enjoy-digital** [comment]
Thanks @mateusz-holenko, as discussed together and described in https://github.com/litex-hub/linux-on-litex-vexriscv/issues/131, we should probably just build the linux kernel from a branch of the linux repo. Can you give the location of the repo you are using to create the patches? I could switch the buildroot kernel build to it.

**Comment by mateusz-holenko** [comment]
@enjoy-digital We developed it in our internal repository that is not visible publicly.

For the testing purposes I created two branches in litex-hub/linux that include all the current LiteX drivers+ the new SDCard one:
* https://github.com/litex-hub/linux/tree/litex-vexriscv--sd_card (based on a current Linux 5.7)
* https://github.com/litex-hub/linux/tree/litex-vexriscv--linux5.0_sd_card (based on Linux 5.0 - this is more/less the same version used by BUILDROOT).

We are currently testing them on HW to make sure everything works fine and once it's done we could switch to one of them in buildroot.

**Comment by enjoy-digital** [comment]
Thanks, merged. I'm going to test it on Nexys4DDR or another board with SDCard.

**Comment by mateusz-holenko** [comment]
Thanks.

We were able to boot the whole system using https://github.com/litex-hub/linux/tree/litex-vexriscv--linux5.0_sd_card branch, but there are some problems with detecting partitions on SDCard. It works fine until you reset the board (we are testing on Arty). We are actively looking into this.

We were not able to boot https://github.com/litex-hub/linux/tree/litex-vexriscv--sd_card branch. We'll look into this later.

**Comment by enjoy-digital** [comment]
@mateusz-holenko: ok thanks, i've also been able to boot the Linux with this branch. To go further, i also switched the Linux Kernel build with Buildroot to this branch: https://github.com/litex-hub/linux-on-litex-vexriscv/issues/131, this will avoid having to handle the patches. When things will be working on your side (or for now features) you could just create a PR to update the kernel branch/commit in the buildroot defconfig.

**Comment by mateusz-holenko** [comment]
For the record: we compared https://github.com/litex-hub/linux/tree/litex-vexriscv--linux5.0_sd_card built in two configurations: by buildroot and "manually" and the buildroot version works fine - there are no problem with detecting partitions on the SD card.

Only when we build it outside buildroot we encounter problems. From looking at the diffs of `.config` files we discovered only one - the version of GCC (buildroot uses 80400 and we locally have 90200).

**Comment by enjoy-digital** [comment]
@mateusz-holenko: thanks for the update, i still need to work on a few things before being able to test but that's good to know. I'll keep you updated when i'll have tested it.

**Pull request merged**
