### PR TITLE
add schoko support and usb host configs resolves #288

### LINKED ISSUE #288: USB host support
I have designed an FPGA-based computer (Schoko) that runs Linux and has video output thanks to LiteX and this project. The computer has a USB host port wired directly to the FPGA, with 15K pull-downs. I know that LiteX has a USB OHCI wrapper module and apparently at least one project has accomplished USB keyboard/mouse support in Linux using LiteX, but I don't believe there is an open-source solution available yet.

In short, it would be great if linux-on-litex had USB host support.

### PR DESCRIPTION
**Pull request by machdyne**
I've added support for the Schoko computer (a litex-boards PR is also pending) and config files for USB host support.

This can be built with:

```
$ make BR2_EXTERNAL=../linux-on-litex-vexriscv/buildroot/ litex_vexriscv_usbhost_defconfig
```

### CODE REVIEW

**Comment by Dolu1990** [comment]
Hi ^^
Thanks :D

How big the cpio and linux Image are with those feature additions ?

**Comment by machdyne** [comment]
8.1M Image
3.5M rootfs.cpio

I have the WLAN options enabled but I haven't been able to get USB wifi working yet.

BTW something that might be useful to add is this line to the default /etc/inittab:
::respawn:/sbin/getty -L 115200 tty0

This brings up a login prompt under the penguin and lets you login with a USB keyboard.

**Comment by Dolu1990** [comment]
> 8.1M Image

It may already overflow the default ramfs size ^^ (8.0MiB)

What's about instead of extending the current default buildconfig, we add one with your config ?
ex : 
linux-on-litex-vexriscv/buildroot_usb_host ?

> I have the WLAN options enabled but I haven't been able to get USB wifi working yet.

Ahhh WLAN is realy a paine in the ass to enable all the proper configs, i had it once working via a SPI dongle, but not easy.
never tried with USB

> BTW something that might be useful to add is this line to the default /etc/inittab:
::respawn:/sbin/getty -L 115200 tty0
This brings up a login prompt under the penguin and lets you login with a USB keyboard.

Nice to know :D
Sure

Thanks :)

**Comment by machdyne** [comment]
I made those changes, please let me know if I need to do anything differently.

I removed the WLAN options but the Image size is now ~8.5M ... it still boots and seems to work fine, but I do see this:

```
[   22.830562] Initramfs unpacking failed: invalid magic at start of compressed archive
[   24.153895] Freeing initrd memory: 8192K
```

I have also tested USB ethernet and it works great.

**Comment by Dolu1990** [comment]
> It may already overflow the default ramfs size ^^ (8.0MiB)

Hooo my bad, you are all good, i mixed cpio and kernel size

Also, stupid me, instead of having a separated buildroot_usb_host folder, the best would be to add a defconfig in : 
https://github.com/litex-hub/linux-on-litex-vexriscv/tree/master/buildroot/configs

and adding an alternative linux.config in https://github.com/litex-hub/linux-on-litex-vexriscv/blob/master/buildroot/board/litex_vexriscv/linux.config

That way, we will avoid duplicating the whole thing :)

Sorry, i didn't tinked about it

> I have also tested USB ethernet and it works great.

Nice :D

Which usb dongle did you used ? there is quite a few which would not work (require USB high speed)

> Initramfs unpacking failed: invalid magic at start of compressed archive

no worries about it, i always had it

**Comment by Dolu1990** [comment]
Look good to me, Thanks :D

**Comment by machdyne** [comment]
I removed the last commit and there is now:

buildroot/configs/litex_vexriscv_usbhost_defconfig
and
buildroot/board/litex_vexriscv/linux_usbhost.config

It might also make sense to create a separate board directory (litex_vexriscv_usbhost?) in order to add the inittab entry to a separate rootfs_overlay so the login prompt shows up when using the USB host configs?

The ethernet dongle I used was a "Giochem" USB 2.0 10/100Mbps RTL8152 USB ethernet adapter with the option:

```
CONFIG_USB_RTL8152=y
```

**Comment by machdyne** [comment]
The tests should now pass as the litex-boards PR for Schoko has been merged.

**Comment by machdyne** [comment]
I was doing --with-coherent-dma on the command line, I've now enabled it in make.py when usb_host is enabled.

**Comment by Dolu1990** [comment]
Hoo nice catch :)
Running regressions

**Comment by enjoy-digital** [comment]
Thanks @machdyne for the board support and USB-Host integration! This merged.

**Pull request merged**
