### PR TITLE
Add threads argument to simulation

### PR DESCRIPTION
**Pull request by developandplay**
Utilize verilator threads to speed up simulation #220

### CODE REVIEW

**Comment by Dolu1990** [comment]
@developandplay Hi ^^
Do you get a good speedup ? I remember testing it with "old" verilator version, at that time, on small to "medium"  design it was slowing things down.

**Comment by developandplay** [comment]
You might be right.
My initial success came from testing rocket and blackparrot in litex-sim.
I'm doing some more tests with vexriscv right now.

**Comment by developandplay** [comment]
I did test a few configurations of threads but in case of vexriscv more threads result in more slow down.
Are Rocket and Blackparrot so much bigger in size that for them the threads become a benefit?

**Comment by Dolu1990** [comment]
It realy depend the configs, but Vex can be multiple times smaller on FPGA than ASIC oriented cores put on FPGA. Also, in simulation there may be some threshold points where the design is just too big to fit in the 1 CPU L2 cache, and performance degrade realy fast ?

With how many softcpu did you tested all of thoses ? With FPU ?

**Comment by Dolu1990** [comment]
(And the design is small enough that a single CPU can simulate it faster than multiple CPU having to syncronise with each others)

**Comment by developandplay** [comment]
> With how many softcpu did you tested all of thoses ? With FPU ?

So far just the default single core configuration. I'll see if multicores or cores with FPU behave differently.

**Comment by enjoy-digital** [comment]
@developandplay: Thanks, I'm merging but as discussed here I'm not sure to have already seen a real speed up (I've only been testing on Intel machine, this could be different on AMD ones).

**Comment by developandplay** [comment]
Oh yes sorry I forgot about this PR.
I'll do some testing the next few days.
At this point I'm also not sure anymore how much of a difference it really
makes.
CPU frequency is just so much more important...

enjoy-digital ***@***.***> schrieb am Di., 21. Sept. 2021,
13:04:

**Pull request merged**
