### PR TITLE
linux: litex_liteuart: add liteuart driver

### PR DESCRIPTION
**Pull request by mateusz-holenko**
This adds LiteX UART (liteuart) driver and configures Linux to use this device as system console.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @mateusz-holenko! Can you explain how you tested it? I just re-compiled the images and tried it with the simulator but it does not seem to be working.

**Comment by enjoy-digital** [comment]
Sorry, that was just my computer that was a bit slow and logs messages appear a bit later than before, that's working fine, thanks!

**Comment by mateusz-holenko** [comment]
Thanks!

FYI I've tested it on Arty board and in [Renode](http://renode.io).

**Comment by enjoy-digital** [comment]
Good, do you have instructions on how to run it with Renode? I'd like to test it and add instructions to the README for it.

**Comment by mateusz-holenko** [comment]
Renode supports [litex with vexriscv.linux](https://github.com/renode/renode/blob/master/scripts/single-node/litex_vexriscv_linux.resc) platform.

You can simulate it by starting Renode and typing in monitor:
 ```
start @scripts/single-node/litex_vexriscv_linux.resc
```
This will, however, use pre-defined binaries from our server.

If you want to use your own binaries, most probably from [linux-on-litex-vexrsicv-prebuilt](https://github.com/litex-hub/linux-on-litex-vexriscv-prebuilt), you should clone the repo and execute the following commands in Renode monitor:

```
set kernel @path-to-repo/linux-on-litex-vexriscv-prebuilt/buildroot/Image
set rootfs @path-to-repo/linux-on-litex-vexriscv-prebuilt/buildroot/rootfs.cpio
set dtb @path-to-repo/linux-on-litex-vexriscv-prebuilt/buildroot/rv32.dtb
set emulator @path-to-repo/linux-on-litex-vexriscv-prebuilt/emulator/emulator.bin

start @scripts/single-node/litex_vexriscv_linux.resc
```

*NOTE*: You need to fix paths to match your setup.

*NOTE2*: You need to have the newest Renode from github, as only in [this commit](https://github.com/renode/renode/commit/9bc91159f3eeb85936574f4e2794379231c1348b) I added the option to provide custom binaries to the script. If you use the older version of Renode, you must change the `litex_vexriscv_linux.resc` script manually.

*NOTE3*: I noticed that the current version of DTB on [linux-on-litex-vexrsicv-prebuilt](https://github.com/litex-hub/linux-on-litex-vexriscv-prebuilt) is outdated. I created a PR fixing this: https://github.com/litex-hub/linux-on-litex-vexriscv-prebuilt/pull/1.

More information on Renode can be found in [README](https://github.com/renode/renode#installation) and [the documentation](https://renode.readthedocs.io/en/latest/index.html).

**Comment by mithro** [comment]
@enjoy-digital There is also a tool which generates the Renode configuration from the LiteX CSV file @ https://github.com/litex-hub/litex-renode

**Comment by mithro** [comment]
@mateusz-holenko Can you update the README for the litex-renode repo to include some usage instructions?

**Comment by mithro** [comment]
@enjoy-digital - Oh FYI -- there is an example of the Linux.conf.au FPGA Miniconf tutorial using Renode + RISC-V (verse or1k and QEMU) avalible at https://github.com/timvideos/litex-buildenv/wiki/HowTo-LCA2018-FPGA-Miniconf-VexRiscv-Renode

**Comment by enjoy-digital** [comment]
Thanks @mateusz-holenko, @mithro, i'll test that very soon.

**Comment by mateusz-holenko** [comment]
@mithro I'll update the README today.

**Comment by pdp7** [comment]
@mateusz-holenko I am trying to run LiteX on Linux-VexRiscV with renode.

I ran in the monitor:
```
start @scripts/single-node/litex_vexriscv_linux.resc
```

but i got an error:
```
Object reference not set to an instance of an object
  at System.Collections.Generic.LargeArrayBuilder`1[T].GetBuffer (System.Int32 index) [0x00022] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.LargeArrayBuilder`1[T].CopyTo (System.Collections.Generic.CopyPosition position, T[] array, System.Int32 arrayIndex, System.Int32 count) [0x00041] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.SparseArrayBuilder`1[T].CopyTo (T[] array, System.Int32 arrayIndex, System.Int32 count) [0x0009a] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.SparseArrayBuilder`1[T].ToArray () [0x00028] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Linq.Enumerable+Concat2Iterator`1[TSource].ToArray () [0x00024] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00021] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at Antmicro.Renode.UserInterface.Monitor.RunCommand (AntShell.Commands.ICommandInteraction writer, Antmicro.Renode.UserInterface.Commands.Command command, System.Collections.Generic.IList`1[T] parameters) [0x00406] in <d47614c6567449c69a4ac1c1bdcf6d28>:0 
  at Antmicro.Renode.UserInterface.Monitor.ExecuteCommand (Antmicro.Renode.UserInterface.Tokenizer.Token[] com, AntShell.Commands.ICommandInteraction writer) [0x00133] in <d47614c6567449c69a4ac1c1bdcf6d28>:0 
  at Antmicro.Renode.UserInterface.Monitor.ParseTokens (System.Collections.Generic.IEnumerable`1[T] tokensToParse, AntShell.Commands.ICommandInteraction writer) [0x001d5] in <d47614c6567449c69a4ac1c1bdcf6d28>:0 
  at Antmicro.Renode.UserInterface.Monitor.Parse (System.String cmd, AntShell.Commands.ICommandInteraction writer) [0x001a7] in <d47614c6567449c69a4ac1c1bdcf6d28>:0 
  at Antmicro.Renode.UserInterface.Monitor.ProcessCommand (System.String command, AntShell.Commands.ICommandInteraction writer) [0x00000] in <d47614c6567449c69a4ac1c1bdcf6d28>:0 
  at Antmicro.Renode.UserInterface.Monitor.HandleCommand (System.String cmd, AntShell.Commands.ICommandInteraction ci) [0x00000] in <d47614c6567449c69a4ac1c1bdcf6d28>:0 
  at AntShell.Shell.HandleCommand (System.String cmd, AntShell.Commands.ICommandInteraction ic) [0x000bd] in <892b95394fdf4e18974bb957344bb8b5>:0 
  at AntShell.CommandLine.HandleControlSequence (AntShell.Helpers.ControlSequence seq) [0x00a45] in <892b95394fdf4e18974bb957344bb8b5>:0 
  at AntShell.Terminal.NavigableTerminalEmulator.HandleInput (System.Object input) [0x0002e] in <892b95394fdf4e18974bb957344bb8b5>:0 
  at AntShell.Terminal.NavigableTerminalEmulator.Run (System.Boolean stopOnError) [0x00017] in <892b95394fdf4e18974bb957344bb8b5>:0 
  at AntShell.Shell.Start (System.Boolean stopOnError) [0x000f9] in <892b95394fdf4e18974bb957344bb8b5>:0 
  at Antmicro.Renode.UI.CommandLineInterface+<>c__DisplayClass0_1.<Run>b__3 (System.Object x) [0x00000] in <cbc535240d924f9182150dcd1bce9341>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x0002c] in <d0e12f672b88444ab4b6d9b2ecf20142>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in <d0e12f672b88444ab4b6d9b2ecf20142>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <d0e12f672b88444ab4b6d9b2ecf20142>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00031] in <d0e12f672b88444ab4b6d9b2ecf20142>:0 
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x00012] in <d0e12f672b88444ab4b6d9b2ecf20142>:0 
```

Any idea how I could troubleshoot?

Thanks!

**Pull request merged**
