### PR TITLE
Add support for CAN bus on Linux to Arty, Nexys & Genesys2 Board 

### PR DESCRIPTION
**Pull request by disdi**
This is to add support for controller area network (CAN bus) to Linux on Litex.
It is based on [CTU CAN FD IP Core](https://gitlab.fel.cvut.cz/canbus/ctucanfd_ip_core) developed by Czech Technical University in Prague.

Related MR for  [Litex](https://github.com/enjoy-digital/litex/pull/1871) is also raised.
Related MR for Arty in [litex-boards](https://github.com/litex-hub/litex-boards/pull/556) is also raised.

Complete documentation of usage and testing can be found at [Project Wiki](https://disdi.github.io/librecar-wiki/Linux-bringup.html).

### CODE REVIEW

**Comment by disdi** [comment]
Below pull requests are merged now:

[litex #2007](https://github.com/enjoy-digital/litex/pull/2007)
[litex-boards #570](https://github.com/litex-hub/litex-boards/pull/570/)

Any chance of getting this one also merged ?

**Comment by enjoy-digital** [comment]
Thanks @disdi, I'll think about it. It becoming a bit specific and CAN/Linux related project should be better to also use/demonstrate use of CAN tools/utilities. We have a such project that we developed with @trabucayre and just need to take the time to clean up things before being able to open source it.

**Comment by enjoy-digital** [comment]
Hi @disdi,

Linux-on-LiteX-Vexriscv aims to be a generic Linux project running on LiteX/VexRiscv SoC. With @trabucayre, we are working on improvements and simplifications to avoid integrating overly specific or complex features. The goal is to use it as a basis for any specific Linux project. Your changes and CAN support are a bit too specific for this repo. I recommend having your own Librecar repo, extending this one with your features (and custom CAN scripts, tools, etc.). I just added a link to your project in the LiteX Wiki: https://github.com/enjoy-digital/litex/wiki/Tutorials-Resources.

Thanks for your contribution and sorry for not merging.

Florent

**Comment by disdi** [comment]
@enjoy-digital No worries. Looking forward to your work on improvements and simplifications for Litex.

**Pull request closed without merging**
